/*
 * File generated by TexturePacker - custom exporter by komatr
 *
 * Contains references to each image inside sprite sheet.
 *
 */{% load TransformName %}
namespace game::config::assets
{
{% for sprite in allSprites %}    inline constexpr const char* {{sprite.trimmedName|stripForbiddenSymbols}} = "{{sprite.trimmedName}}";
{% endfor %}
}