/*
 * File generated by TexturePacker - custom exporter by komatr
 *
 * Contains references to each image inside sprite sheet.
 *
 */
namespace game::assets
{
inline constexpr const char* s_gui_tab_manifests = "gui/tab/manifests";
inline constexpr const char* s_gui_tab_marketplace = "gui/tab/marketplace";
inline constexpr const char* s_gui_tab_sabotages = "gui/tab/sabotages";
inline constexpr const char* s_gui_tab_vehicles = "gui/tab/vehicles";
inline constexpr const char* s_gui_vehicle_vehiclePickup = "gui/vehicle/vehiclePickup";
inline constexpr const char* s_gui_vehicle_vehicleTruck = "gui/vehicle/vehicleTruck";
inline constexpr const char* s_gui_vehicle_vehicleVan = "gui/vehicle/vehicleVan";
inline constexpr const char* s_gui_win_bg = "gui/win/bg";
inline constexpr const char* s_gui_win_border = "gui/win/border";
inline constexpr const char* s_gui_win_divH = "gui/win/divH";
inline constexpr const char* s_gui_win_divV = "gui/win/divV";
inline constexpr const char* s_shared_circleBlur = "shared/circleBlur";

} // namespace game::assets