/*
 * File generated by TexturePacker - custom exporter by komatr
 *
 * Contains references to each image inside sprite sheet.
 *
 */


namespace game::constant::assets
{

inline constexpr const char* s_background = "background";

inline constexpr const char* s_border = "border";

inline constexpr const char* s_calendar = "calendar";

inline constexpr const char* s_cancel = "cancel";

inline constexpr const char* s_cart = "cart";

inline constexpr const char* s_chart = "chart";

inline constexpr const char* s_circleBlur = "circleBlur";

inline constexpr const char* s_divH = "divH";

inline constexpr const char* s_divV = "divV";

inline constexpr const char* s_manifests = "manifests";

inline constexpr const char* s_marker = "marker";

inline constexpr const char* s_marketplace = "marketplace";

inline constexpr const char* s_pause = "pause";

inline constexpr const char* s_pickup = "pickup";

inline constexpr const char* s_play = "play";

inline constexpr const char* s_sabotages = "sabotages";

inline constexpr const char* s_select = "select";

inline constexpr const char* s_settings = "settings";

inline constexpr const char* s_truck = "truck";

inline constexpr const char* s_van = "van";

inline constexpr const char* s_vehicles = "vehicles";

} // namespace game::constant::assets
